name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use files from D:\Desktop\sale
        run: |
          cp -r ${{ github.workspace }}/D:/Desktop/sale/* .
          
      # ต่อไปคือคำสั่งที่ให้ GitHub Actions ทำต่อไป
